pipeline {
    agent any

    tools {
        jdk 'JAVA_HOME'
        maven 'M2_HOME'
    }

    environment {
        SONARQUBE = 'SonarQube'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                dir('ecommerce-microservice') {
                    sh 'mvn clean verify'
                }
            }
        }

        stage('Check JaCoCo Report') {
            steps {
                dir('ecommerce-microservice') {
                    sh '''
                    echo "Checking JaCoCo XML..."
                    ls -la target/site/jacoco || true
                    test -f target/site/jacoco/jacoco.xml && echo "FOUND: target/site/jacoco/jacoco.xml" || echo "MISSING: target/site/jacoco/jacoco.xml"
                    '''
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('ecommerce-microservice') {
                    withSonarQubeEnv('SonarQube') {
                        sh '''
                        mvn sonar:sonar \
                        -Dsonar.projectKey=PI-SOYOSA \
                        -Dsonar.projectName=PI-SOYOSA
                        '''
                    }
                }
            }
        }
    }
}
